### ISSUE TITLE
Calculate Position size, R Value, Percent change

### ISSUE THREAD

**Issue by hbeckeri** [beckerich/risk-manager#10]
Look at `createPosition` on line 118 https://github.com/hbeckeri/crypto-cli/blob/master/lib/wallets/BitmexWallet.js

**Comment by scottjstewart** [comment]
(node:22675) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sheetsRegistry' of undefined

**Comment by scottjstewart** [comment]
that error is preventing my compiling. here is the whole thing 
(node:22675) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sheetsRegistry' of undefined
    at Function.module.exports../pages/_document.js.CustomDocument.getInitialProps (/Users/scottstewart/Documents/risk-manager/.next/server/bundles/pages/_document.js:240:29)
    at _callee$ (/Users/scottstewart/Documents/risk-manager/node_modules/next/dist/lib/utils.js:111:30)
    at tryCatch (/Users/scottstewart/Documents/risk-manager/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/scottstewart/Documents/risk-manager/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/scottstewart/Documents/risk-manager/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/scottstewart/Documents/risk-manager/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/Users/scottstewart/Documents/risk-manager/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at /Users/scottstewart/Documents/risk-manager/node_modules/@babel/runtime/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/Users/scottstewart/Documents/risk-manager/node_modules/core-js/library/modules/_export.js:36:28)
    at /Users/scottstewart/Documents/risk-manager/node_modules/@babel/runtime/helpers/asyncToGenerator.js:7:12
    at loadGetInitialProps (/Users/scottstewart/Documents/risk-manager/node_modules/next/dist/lib/utils.js:90:31)
    at _callee3$ (/Users/scottstewart/Documents/risk-manager/node_modules/next/dist/server/render.js:296:51)
    at tryCatch (/Users/scottstewart/Documents/risk-manager/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/scottstewart/Documents/risk-manager/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/scottstewart/Documents/risk-manager/node_modules/regenerator-runtime/runtime.js:114:21)
(node:22675) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejec
tion id: 4)
(node:22675) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by scottjstewart** [comment]
im stuck on it, advice would help or i can pull request so that you can see the code

**Comment by hbeckeri** [comment]
@scottjstewart It's usually caused by another error. Look above it in the logs and that will likely show you what the real error is.

**Comment by hbeckeri** [comment]
@scottjstewart Feel free to create a PR though

**Comment by scottjstewart** [comment]
@hbeckeri
